//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ADT9DB1Entities3 : DbContext
{
    public ADT9DB1Entities3()
        : base("name=ADT9DB1Entities3")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<packageList> packageLists { get; set; }
    public virtual DbSet<packageListItem> packageListItems { get; set; }
    public virtual DbSet<stationaryCatelogue> stationaryCatelogues { get; set; }
    public virtual DbSet<stockTake> stockTakes { get; set; }
    public virtual DbSet<supplierList> supplierLists { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<transactionList> transactionLists { get; set; }
    public virtual DbSet<transactionListItem> transactionListItems { get; set; }
    public virtual DbSet<userDepartmentList> userDepartmentLists { get; set; }
}
